name: Check OpenSSL Static

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-26.04

    steps:
    - name: System Information
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libjitterentropy-dev
        set -x

        uname -a
        cat /etc/os-release

        echo
        echo "========== Compiler =========="
        gcc --version
        ld --version

        echo
        echo "========== OpenSSL =========="
        openssl version -a

        echo
        echo "========== Installed packages =========="
        dpkg -l | grep -E 'ssl|crypto|jitter|jent'

        echo
        echo "========== libssl-dev =========="
        apt-cache policy libssl-dev

        echo
        echo "========== Files =========="
        ls -l /usr/lib/x86_64-linux-gnu/libcrypto*
        ls -l /usr/lib/x86_64-linux-gnu/libssl*

        echo
        echo "========== Search jitter =========="
        find /usr -iname '*jitter*' -o -iname '*jent*'

        echo
        echo "========== pkg-config =========="
        pkg-config --libs openssl || true
        pkg-config --cflags openssl || true

        echo
        echo "========== libcrypto.a contains =========="
        ar t /usr/lib/x86_64-linux-gnu/libcrypto.a | grep jitter || true

        echo
        echo "========== Undefined jent symbols =========="
        nm -A /usr/lib/x86_64-linux-gnu/libcrypto.a | grep jent_ || true

        echo
        echo "========== Dynamic symbols =========="
        nm -D /usr/lib/x86_64-linux-gnu/libcrypto.so.3 | grep jent_ || true

    - name: Build test (dynamic)
      shell: bash
      run: |
        cat > test.c <<EOF
        #include <openssl/rand.h>

        int main(void)
        {
            unsigned char b[32];
            return RAND_bytes(b, sizeof(b)) != 1;
        }
        EOF

        gcc test.c -lcrypto -o test-dynamic

        echo
        echo "========== ldd =========="
        ldd test-dynamic

        ./test-dynamic

    - name: Build test (static)
      shell: bash
      run: |
        set -x

        gcc \
          -static \
          test.c \
          -o test-static \
          -lcrypto
