name: Run Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
          - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: execute py script
        run: |
          python get-china-ip.py
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: china-ip-ranges-*.txt
